version: "3.8"

services:
  building:
    build: ./building
    networks:
      - network
    image: lab5
  test:
    build: ./test
    networks:
      - network
    depends_on:
      - build

networks:
  network:
    driver: bridge