version: "3.8"

services:
  building:
    build: ./building
    networks:
      - network
    image: lab5
    volumes:
      - ./artifacts:/app/build
  test:
    build: ./test
    networks:
      - network
    depends_on:
      - building

networks:
  network:
    driver: bridge