version: "3.8"

services:
  building:
    build: ./building
    networks:
      - network
    image: react-hot-cold:latest
    volumes:
    - $(PWD)/artefakty:/react-hot-cold/build
  test:
    build: ./test
    networks:
      - network
    depends_on:
      - building

networks:
  network:
    driver: bridge

